version: '2.3'

services:
  backend:
    image: schbang-q-backend
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DB_URL=mongodb://mongodb:27017/schbang-q-db
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db

volumes:
  data: