version: '2.3'

services:
  backend:
    image: schbang-q-backend
    build: .
    ports:
      - '80:80'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db

volumes:
  data: